import '../js/filter.js'
import '../js/film.js'
import '../js/fetchData.js'
import '../js/favorite.js'
import '../js/createElement.js'
import '../js/constants.js'
import '../js/pagination.js'
import '../js/main.js'